version: 0.2

phases:
  install:
    commands:
      - echo "No build needed"
  build:
    commands:
      - echo "No build step"
  post_build:
    commands:
      - aws s3 sync . s3://ultimatetimer-front --delete

artifacts:
  files:
    - '**/*'
